# mysql
# nginx
# wordpress
# php-fpm

---
######################################################################### mysql
- name: Install Mysql package
  yum: name={{ item }} state=present
  with_items:
    - mysql-devel
    - mysql-server
    - libselinux-python
    - libsemanage-python

- name: Install mysql python module (via yum)
  when: not ansible_distribution == 'Amazon'
  yum:
    name:  MySQL-python
    state: present

# SEE ALSO: http://qiita.com/creasty/items/9b2b4680af56c4f86dee
- name: Install mysql python module (from source)
  when: ansible_distribution == 'Amazon' # Amazon Linux AMI
  command: 'bash -lc "{{ item }}"'
  with_items:
    - 'cd /usr/tmp && wget http://download.sourceforge.net/sourceforge/mysql-python/MySQL-python-1.2.3.tar.gz'
    - 'cd /usr/tmp && tar xvzf /usr/tmp/MySQL-python-1.2.3.tar.gz'
    - 'cd /usr/tmp/MySQL-python-1.2.3 && python setup.py build'
    - 'cd /usr/tmp/MySQL-python-1.2.3 && python setup.py install'
    - 'rm -rf /usr/tmp/MySQL-python*'

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes
  when: ansible_selinux.status == "enabled"

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: restart mysql

- name: Start Mysql Service
  service: name=mysqld state=started enabled=yes

######################################################################## nginx
- name: Install nginx
  yum: name=nginx state=present

- name: Create nginx htpasswd
  htpasswd: path=/etc/nginx/.htpasswd name={{ nginx_htpasswd_name }} password={{ nginx_htpasswd_password }} owner=root group=root mode=0640

- name: Copy nginx configuration for wordpress
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: Copy nginx configuration for wordpress
  copy: src=mime.types dest=/etc/nginx/mime.types
  notify: restart nginx

- name: Copy nginx configuration for wordpress
  template: src=conf.d/default.conf.j2 dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: Start nginx Service
  service: name=nginx state=started enabled=yes

######################################################################## wordpress
- name: Download Wordpress
  get_url: url=http://ja.wordpress.org/wordpress-{{ wp_version }}.tar.gz dest=/srv/wordpress-{{ wp_version }}.tar.gz

- name: Extract archive
  command: chdir=/srv/ /bin/tar xvf wordpress-{{ wp_version }}.tar.gz creates=/srv/wordpress

- name: Fetch random salts for Wordpress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  sudo: no

- name: Create Wordpress database
  mysql_db: name={{ wp_db_name }} state=present

- name: Create Wordpress database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host='localhost' state=present

# - name: Copy Wordpress config file
#   template: src=wp-config.php.j2 dest=/srv/wordpress/

# SEE ALSO: https://github.com/ansible/ansible/issues/9526
- name: Copy Wordpress config file
  template: src=wp-config.php.j2 dest=/tmp/
- name: Move Wordpress config file
  command: mv /tmp/wp-config.php /srv/wordpress/

- name: Change ownership of Wordpress installation
  file: path=/srv/wordpress/ owner={{ wp_user }} group={{ wp_user }} state=directory recurse=yes

######################################################################## php
- name: Install php-fpm and deps
  yum: name={{ item }} state=present enablerepo=remi,remi-php56
  with_items:
    - php
    - php-fpm
    - php-enchant
    - php-IDNA_Convert
    - php-mbstring
    - php-mysql
    - php-PHPMailer
    - php-process
    - php-simplepie
    - php-xml
    - php-gd
    - php-mcrypt
    - phpMyAdmin

- name: Change mode of session save path
  file: path=/var/lib/php/session mode=0777 state=directory recurse=yes

- name: Disable default pool
  command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.disabled creates=/etc/php-fpm.d/www.disabled
  notify: restart php-fpm

- name: Copy php-fpm configuration
  template: src=wordpress.conf.j2 dest=/etc/php-fpm.d/
  notify: restart php-fpm

- name: Start php-fpm Service
  service: name=php-fpm state=started enabled=yes
